server:
  port: 9001

spring:
  application:
    name: log4M
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:./data/log4m;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
mybatis-plus:
  type-aliases-package: com.tony.log4m.pojo.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      id-type: auto
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:logback.xml

botToken: "yourBotToken"