server:
  port: 8080

spring:
  application:
    # 应用名称
    name: log4M
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nunu
    url: jdbc:mysql://localhost:3306/log4m?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tony.log4m.pojo.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:logback.xml
