CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ACCOUNT_ID    INTEGER AUTO_INCREMENT,
    ACCOUNT_NAME  CHARACTER VARYING(255)                NOT NULL,
    BALANCE       NUMERIC(10, 2) DEFAULT 0.00           NOT NULL,
    BUDGET NUMERIC(10, 2) DEFAULT 0.00 NULL,
    CONSUME       NUMERIC(10, 2) DEFAULT 0.00           NOT NULL,
    INCOME        NUMERIC(10, 2) DEFAULT 0.00           NOT NULL,
    CONSUME_LIMIT NUMERIC(10, 2) DEFAULT 0.00           NOT NULL,
    SORT          INTEGER        DEFAULT 99             NOT NULL,
    STATUS        INTEGER        DEFAULT 1              NOT NULL,
    IS_DEFAULT    TINYINT        DEFAULT 0              NOT NULL,
    DELETED       TINYINT        DEFAULT 0              NOT NULL,
    CR_TIME       TIMESTAMP      DEFAULT LOCALTIMESTAMP NOT NULL,
    MD_TIME       TIMESTAMP      DEFAULT LOCALTIMESTAMP NOT NULL,
    PRIMARY KEY (ACCOUNT_ID)
);

ALTER TABLE ACCOUNT
    ADD COLUMN IF NOT EXISTS budget NUMERIC(10, 2) DEFAULT 0.00 NOT NULL AFTER BALANCE;


CREATE TABLE IF NOT EXISTS BILL
(
    BILL_ID              INTEGER AUTO_INCREMENT,
    ACCOUNT_ID           INTEGER                DEFAULT 0,
    TRANSACTION_TYPE     CHARACTER VARYING(32)                         NOT NULL,
    BILL_DATE            DATE                   DEFAULT LOCALTIMESTAMP NOT NULL,
    BILL_MONTH           CHARACTER(7)                                  NOT NULL,
    AMOUNT               NUMERIC(10, 2)                                NOT NULL,
    PARENT_CATEGORY_ID   INTEGER                DEFAULT 0,
    PARENT_CATEGORY_NAME CHARACTER VARYING(255) DEFAULT '',
    CATEGORY_ID          INTEGER                DEFAULT 0,
    CATEGORY_NAME        CHARACTER VARYING(255) DEFAULT '',
    TAG_ID               INTEGER                DEFAULT 0,
    TAG_NAME             CHARACTER VARYING(255) DEFAULT '',
    LEDGER_ID            INTEGER                DEFAULT 0,
    LEDGER_NAME          CHARACTER VARYING(255) DEFAULT '',
    NOTE                 CHARACTER VARYING(255) DEFAULT '',
    CURRENCY             CHARACTER VARYING(255) DEFAULT '',
    DELETED              TINYINT                DEFAULT 0              NOT NULL,
    CR_TIME              TIMESTAMP              DEFAULT LOCALTIMESTAMP NOT NULL,
    MD_TIME              TIMESTAMP              DEFAULT LOCALTIMESTAMP NOT NULL,
    PRIMARY KEY (BILL_ID)
);


CREATE TABLE IF NOT EXISTS CATEGORY
(
    CATEGORY_ID          INTEGER AUTO_INCREMENT,
    PARENT_CATEGORY_ID   INTEGER                DEFAULT 0,
    CATEGORY_NAME        CHARACTER VARYING(255)                        NOT NULL,
    SORT                 INTEGER                DEFAULT 99             NOT NULL,
    DELETED              TINYINT                DEFAULT 0              NOT NULL,
    CR_TIME              TIMESTAMP              DEFAULT LOCALTIMESTAMP NOT NULL,
    MD_TIME              TIMESTAMP              DEFAULT LOCALTIMESTAMP NOT NULL,
    PARENT_CATEGORY_NAME CHARACTER VARYING(255) DEFAULT '',
    PRIMARY KEY (CATEGORY_ID)
);

ALTER TABLE CATEGORY
    ADD COLUMN IF NOT EXISTS is_default TINYINT DEFAULT 0 NOT NULL AFTER SORT;



CREATE TABLE IF NOT EXISTS LEDGER
(
    LEDGER_ID   INTEGER AUTO_INCREMENT,
    LEDGER_NAME CHARACTER VARYING(255)           NOT NULL,
    DELETED     TINYINT   DEFAULT 0              NOT NULL,
    CR_TIME     TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    MD_TIME     TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    PRIMARY KEY (LEDGER_ID)
);

CREATE TABLE IF NOT EXISTS RULE
(
    RULE_ID          INTEGER AUTO_INCREMENT,
    RULE_NAME        CHARACTER VARYING(255)              NOT NULL,
    ACCOUNT_ID       INTEGER                DEFAULT 0,
    TRANSACTION_TYPE CHARACTER VARYING(32)               NOT NULL,
    CATEGORY_ID      INTEGER                DEFAULT 0,
    TAG_ID           INTEGER                DEFAULT 0,
    AMOUNT           NUMERIC(10, 2)         DEFAULT 0.00 NOT NULL,
    KEYWORDS         CHARACTER VARYING(255) DEFAULT '',
    SORT             INTEGER                DEFAULT 99   NOT NULL,
    CR_TIME          TIMESTAMP              DEFAULT LOCALTIMESTAMP,
    MD_TIME          TIMESTAMP              DEFAULT LOCALTIMESTAMP,
    DELETED          TINYINT                DEFAULT 0,
    PRIMARY KEY (RULE_ID)
);


CREATE TABLE IF NOT EXISTS SYS_USER
(
    USER_ID            INTEGER AUTO_INCREMENT,
    USERNAME           CHARACTER VARYING(255) DEFAULT '',
    TG_USER_ID LONG DEFAULT 0,
    PASSWORD           CHARACTER VARYING(255) DEFAULT '',
    EMAIL              CHARACTER VARYING(255) DEFAULT '',
    DEFAULT_ACCOUNT_ID INTEGER                DEFAULT 0,
    STATUS             INTEGER                DEFAULT 1              NOT NULL,
    DELETED            TINYINT                DEFAULT 0              NOT NULL,
    CR_TIME            TIMESTAMP              DEFAULT LOCALTIMESTAMP NOT NULL,
    MD_TIME            TIMESTAMP              DEFAULT LOCALTIMESTAMP NOT NULL,
    PRIMARY KEY (USER_ID)
);


CREATE TABLE IF NOT EXISTS TAG
(
    TAG_ID   INTEGER AUTO_INCREMENT,
    TAG_NAME CHARACTER VARYING(255)           NOT NULL,
    SORT     INTEGER   DEFAULT 99             NOT NULL,
    DELETED  TINYINT   DEFAULT 0              NOT NULL,
    CR_TIME  TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    MD_TIME  TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    PRIMARY KEY (TAG_ID)
);


